image: gitpod/workspace-full:commit-8db1f225de966b92cb30b42665527cdd348e94b9

tasks:
  - name: Maven Package
    init: ./mvnw package
  #- name: Docker Pull
  #  init: docker-compose -f ./devtools/docker-compose.yml pull

vscode:
  extensions:
    - redhat.java
