image: gitpod/workspace-full:commit-2e5340ee0f9c39aef3f499ba7a5466087e700fb9

tasks:
  - name: Maven Package
    init: ./mvnw package
  #- name: Docker Pull
  #  init: docker-compose -f ./devtools/docker-compose.yml pull

vscode:
  extensions:
    - redhat.java
